[project]
name = "checklinks"
version = "0.1.0"
dependencies = ["typer[all]"]
requires-python = ">=3.7"

[project.scripts]
checklinks = "checklinks.cli.__main__:app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"